/*
 * GENERATED by tools/generate_gles1.py - do not edit.
 *
 * lifted from the system GLES headers so the softfp/hardfp bridges in
 * thunk_gen_dyn.h can be generated from real signatures.
 */
#pragma once

#include <GLES/gl.h>
#include <GLES/glext.h>

typedef void (*PFN_glActiveTexture)(GLenum texture);
static PFN_glActiveTexture glad_glActiveTexture = nullptr;
typedef void (*PFN_glAlphaFunc)(GLenum func, GLfloat ref);
static PFN_glAlphaFunc glad_glAlphaFunc = nullptr;
typedef void (*PFN_glAlphaFuncx)(GLenum func, GLfixed ref);
static PFN_glAlphaFuncx glad_glAlphaFuncx = nullptr;
typedef void (*PFN_glBindBuffer)(GLenum target, GLuint buffer);
static PFN_glBindBuffer glad_glBindBuffer = nullptr;
typedef void (*PFN_glBindFramebufferOES)(GLenum target, GLuint framebuffer);
static PFN_glBindFramebufferOES glad_glBindFramebufferOES = nullptr;
typedef void (*PFN_glBindRenderbufferOES)(GLenum target, GLuint renderbuffer);
static PFN_glBindRenderbufferOES glad_glBindRenderbufferOES = nullptr;
typedef void (*PFN_glBindTexture)(GLenum target, GLuint texture);
static PFN_glBindTexture glad_glBindTexture = nullptr;
typedef void (*PFN_glBlendEquationOES)(GLenum mode);
static PFN_glBlendEquationOES glad_glBlendEquationOES = nullptr;
typedef void (*PFN_glBlendEquationSeparateOES)(GLenum modeRGB, GLenum modeAlpha);
static PFN_glBlendEquationSeparateOES glad_glBlendEquationSeparateOES = nullptr;
typedef void (*PFN_glBlendFunc)(GLenum sfactor, GLenum dfactor);
static PFN_glBlendFunc glad_glBlendFunc = nullptr;
typedef void (*PFN_glBlendFuncSeparateOES)(GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha);
static PFN_glBlendFuncSeparateOES glad_glBlendFuncSeparateOES = nullptr;
typedef void (*PFN_glBufferData)(GLenum target, GLsizeiptr size, const void *data, GLenum usage);
static PFN_glBufferData glad_glBufferData = nullptr;
typedef void (*PFN_glBufferSubData)(GLenum target, GLintptr offset, GLsizeiptr size, const void *data);
static PFN_glBufferSubData glad_glBufferSubData = nullptr;
typedef GLenum (*PFN_glCheckFramebufferStatusOES)(GLenum target);
static PFN_glCheckFramebufferStatusOES glad_glCheckFramebufferStatusOES = nullptr;
typedef void (*PFN_glClear)(GLbitfield mask);
static PFN_glClear glad_glClear = nullptr;
typedef void (*PFN_glClearColor)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
static PFN_glClearColor glad_glClearColor = nullptr;
typedef void (*PFN_glClearColorx)(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
static PFN_glClearColorx glad_glClearColorx = nullptr;
typedef void (*PFN_glClearDepthf)(GLfloat d);
static PFN_glClearDepthf glad_glClearDepthf = nullptr;
typedef void (*PFN_glClearDepthx)(GLfixed depth);
static PFN_glClearDepthx glad_glClearDepthx = nullptr;
typedef void (*PFN_glClearStencil)(GLint s);
static PFN_glClearStencil glad_glClearStencil = nullptr;
typedef void (*PFN_glClientActiveTexture)(GLenum texture);
static PFN_glClientActiveTexture glad_glClientActiveTexture = nullptr;
typedef void (*PFN_glClipPlanef)(GLenum p, const GLfloat *eqn);
static PFN_glClipPlanef glad_glClipPlanef = nullptr;
typedef void (*PFN_glClipPlanex)(GLenum plane, const GLfixed *equation);
static PFN_glClipPlanex glad_glClipPlanex = nullptr;
typedef void (*PFN_glColor4f)(GLfloat red, GLfloat green, GLfloat blue, GLfloat alpha);
static PFN_glColor4f glad_glColor4f = nullptr;
typedef void (*PFN_glColor4ub)(GLubyte red, GLubyte green, GLubyte blue, GLubyte alpha);
static PFN_glColor4ub glad_glColor4ub = nullptr;
typedef void (*PFN_glColor4x)(GLfixed red, GLfixed green, GLfixed blue, GLfixed alpha);
static PFN_glColor4x glad_glColor4x = nullptr;
typedef void (*PFN_glColorMask)(GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha);
static PFN_glColorMask glad_glColorMask = nullptr;
typedef void (*PFN_glColorPointer)(GLint size, GLenum type, GLsizei stride, const void *pointer);
static PFN_glColorPointer glad_glColorPointer = nullptr;
typedef void (*PFN_glCompressedTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLsizei width, GLsizei height, GLint border, GLsizei imageSize, const void *data);
static PFN_glCompressedTexImage2D glad_glCompressedTexImage2D = nullptr;
typedef void (*PFN_glCompressedTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLsizei imageSize, const void *data);
static PFN_glCompressedTexSubImage2D glad_glCompressedTexSubImage2D = nullptr;
typedef void (*PFN_glCopyTexImage2D)(GLenum target, GLint level, GLenum internalformat, GLint x, GLint y, GLsizei width, GLsizei height, GLint border);
static PFN_glCopyTexImage2D glad_glCopyTexImage2D = nullptr;
typedef void (*PFN_glCopyTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLint x, GLint y, GLsizei width, GLsizei height);
static PFN_glCopyTexSubImage2D glad_glCopyTexSubImage2D = nullptr;
typedef void (*PFN_glCullFace)(GLenum mode);
static PFN_glCullFace glad_glCullFace = nullptr;
typedef void (*PFN_glCurrentPaletteMatrixOES)(GLuint matrixpaletteindex);
static PFN_glCurrentPaletteMatrixOES glad_glCurrentPaletteMatrixOES = nullptr;
typedef void (*PFN_glDeleteBuffers)(GLsizei n, const GLuint *buffers);
static PFN_glDeleteBuffers glad_glDeleteBuffers = nullptr;
typedef void (*PFN_glDeleteFramebuffersOES)(GLsizei n, const GLuint *framebuffers);
static PFN_glDeleteFramebuffersOES glad_glDeleteFramebuffersOES = nullptr;
typedef void (*PFN_glDeleteRenderbuffersOES)(GLsizei n, const GLuint *renderbuffers);
static PFN_glDeleteRenderbuffersOES glad_glDeleteRenderbuffersOES = nullptr;
typedef void (*PFN_glDeleteTextures)(GLsizei n, const GLuint *textures);
static PFN_glDeleteTextures glad_glDeleteTextures = nullptr;
typedef void (*PFN_glDepthFunc)(GLenum func);
static PFN_glDepthFunc glad_glDepthFunc = nullptr;
typedef void (*PFN_glDepthMask)(GLboolean flag);
static PFN_glDepthMask glad_glDepthMask = nullptr;
typedef void (*PFN_glDepthRangef)(GLfloat n, GLfloat f);
static PFN_glDepthRangef glad_glDepthRangef = nullptr;
typedef void (*PFN_glDepthRangex)(GLfixed n, GLfixed f);
static PFN_glDepthRangex glad_glDepthRangex = nullptr;
typedef void (*PFN_glDisable)(GLenum cap);
static PFN_glDisable glad_glDisable = nullptr;
typedef void (*PFN_glDisableClientState)(GLenum array);
static PFN_glDisableClientState glad_glDisableClientState = nullptr;
typedef void (*PFN_glDrawArrays)(GLenum mode, GLint first, GLsizei count);
static PFN_glDrawArrays glad_glDrawArrays = nullptr;
typedef void (*PFN_glDrawElements)(GLenum mode, GLsizei count, GLenum type, const void *indices);
static PFN_glDrawElements glad_glDrawElements = nullptr;
typedef void (*PFN_glDrawTexfOES)(GLfloat x, GLfloat y, GLfloat z, GLfloat width, GLfloat height);
static PFN_glDrawTexfOES glad_glDrawTexfOES = nullptr;
typedef void (*PFN_glDrawTexfvOES)(const GLfloat *coords);
static PFN_glDrawTexfvOES glad_glDrawTexfvOES = nullptr;
typedef void (*PFN_glDrawTexiOES)(GLint x, GLint y, GLint z, GLint width, GLint height);
static PFN_glDrawTexiOES glad_glDrawTexiOES = nullptr;
typedef void (*PFN_glDrawTexivOES)(const GLint *coords);
static PFN_glDrawTexivOES glad_glDrawTexivOES = nullptr;
typedef void (*PFN_glDrawTexsOES)(GLshort x, GLshort y, GLshort z, GLshort width, GLshort height);
static PFN_glDrawTexsOES glad_glDrawTexsOES = nullptr;
typedef void (*PFN_glDrawTexsvOES)(const GLshort *coords);
static PFN_glDrawTexsvOES glad_glDrawTexsvOES = nullptr;
typedef void (*PFN_glDrawTexxOES)(GLfixed x, GLfixed y, GLfixed z, GLfixed width, GLfixed height);
static PFN_glDrawTexxOES glad_glDrawTexxOES = nullptr;
typedef void (*PFN_glDrawTexxvOES)(const GLfixed *coords);
static PFN_glDrawTexxvOES glad_glDrawTexxvOES = nullptr;
typedef void (*PFN_glEGLImageTargetRenderbufferStorageOES)(GLenum target, GLeglImageOES image);
static PFN_glEGLImageTargetRenderbufferStorageOES glad_glEGLImageTargetRenderbufferStorageOES = nullptr;
typedef void (*PFN_glEGLImageTargetTexture2DOES)(GLenum target, GLeglImageOES image);
static PFN_glEGLImageTargetTexture2DOES glad_glEGLImageTargetTexture2DOES = nullptr;
typedef void (*PFN_glEnable)(GLenum cap);
static PFN_glEnable glad_glEnable = nullptr;
typedef void (*PFN_glEnableClientState)(GLenum array);
static PFN_glEnableClientState glad_glEnableClientState = nullptr;
typedef void (*PFN_glFinish)(void);
static PFN_glFinish glad_glFinish = nullptr;
typedef void (*PFN_glFlush)(void);
static PFN_glFlush glad_glFlush = nullptr;
typedef void (*PFN_glFogf)(GLenum pname, GLfloat param);
static PFN_glFogf glad_glFogf = nullptr;
typedef void (*PFN_glFogfv)(GLenum pname, const GLfloat *params);
static PFN_glFogfv glad_glFogfv = nullptr;
typedef void (*PFN_glFogx)(GLenum pname, GLfixed param);
static PFN_glFogx glad_glFogx = nullptr;
typedef void (*PFN_glFogxv)(GLenum pname, const GLfixed *param);
static PFN_glFogxv glad_glFogxv = nullptr;
typedef void (*PFN_glFramebufferRenderbufferOES)(GLenum target, GLenum attachment, GLenum renderbuffertarget, GLuint renderbuffer);
static PFN_glFramebufferRenderbufferOES glad_glFramebufferRenderbufferOES = nullptr;
typedef void (*PFN_glFramebufferTexture2DOES)(GLenum target, GLenum attachment, GLenum textarget, GLuint texture, GLint level);
static PFN_glFramebufferTexture2DOES glad_glFramebufferTexture2DOES = nullptr;
typedef void (*PFN_glFrontFace)(GLenum mode);
static PFN_glFrontFace glad_glFrontFace = nullptr;
typedef void (*PFN_glFrustumf)(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f);
static PFN_glFrustumf glad_glFrustumf = nullptr;
typedef void (*PFN_glFrustumx)(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f);
static PFN_glFrustumx glad_glFrustumx = nullptr;
typedef void (*PFN_glGenBuffers)(GLsizei n, GLuint *buffers);
static PFN_glGenBuffers glad_glGenBuffers = nullptr;
typedef void (*PFN_glGenFramebuffersOES)(GLsizei n, GLuint *framebuffers);
static PFN_glGenFramebuffersOES glad_glGenFramebuffersOES = nullptr;
typedef void (*PFN_glGenRenderbuffersOES)(GLsizei n, GLuint *renderbuffers);
static PFN_glGenRenderbuffersOES glad_glGenRenderbuffersOES = nullptr;
typedef void (*PFN_glGenTextures)(GLsizei n, GLuint *textures);
static PFN_glGenTextures glad_glGenTextures = nullptr;
typedef void (*PFN_glGenerateMipmapOES)(GLenum target);
static PFN_glGenerateMipmapOES glad_glGenerateMipmapOES = nullptr;
typedef void (*PFN_glGetBooleanv)(GLenum pname, GLboolean *data);
static PFN_glGetBooleanv glad_glGetBooleanv = nullptr;
typedef void (*PFN_glGetBufferParameteriv)(GLenum target, GLenum pname, GLint *params);
static PFN_glGetBufferParameteriv glad_glGetBufferParameteriv = nullptr;
typedef void (*PFN_glGetBufferPointervOES)(GLenum target, GLenum pname, void **params);
static PFN_glGetBufferPointervOES glad_glGetBufferPointervOES = nullptr;
typedef void (*PFN_glGetClipPlanef)(GLenum plane, GLfloat *equation);
static PFN_glGetClipPlanef glad_glGetClipPlanef = nullptr;
typedef void (*PFN_glGetClipPlanex)(GLenum plane, GLfixed *equation);
static PFN_glGetClipPlanex glad_glGetClipPlanex = nullptr;
typedef GLenum (*PFN_glGetError)(void);
static PFN_glGetError glad_glGetError = nullptr;
typedef void (*PFN_glGetFixedv)(GLenum pname, GLfixed *params);
static PFN_glGetFixedv glad_glGetFixedv = nullptr;
typedef void (*PFN_glGetFloatv)(GLenum pname, GLfloat *data);
static PFN_glGetFloatv glad_glGetFloatv = nullptr;
typedef void (*PFN_glGetFramebufferAttachmentParameterivOES)(GLenum target, GLenum attachment, GLenum pname, GLint *params);
static PFN_glGetFramebufferAttachmentParameterivOES glad_glGetFramebufferAttachmentParameterivOES = nullptr;
typedef void (*PFN_glGetIntegerv)(GLenum pname, GLint *data);
static PFN_glGetIntegerv glad_glGetIntegerv = nullptr;
typedef void (*PFN_glGetLightfv)(GLenum light, GLenum pname, GLfloat *params);
static PFN_glGetLightfv glad_glGetLightfv = nullptr;
typedef void (*PFN_glGetLightxv)(GLenum light, GLenum pname, GLfixed *params);
static PFN_glGetLightxv glad_glGetLightxv = nullptr;
typedef void (*PFN_glGetMaterialfv)(GLenum face, GLenum pname, GLfloat *params);
static PFN_glGetMaterialfv glad_glGetMaterialfv = nullptr;
typedef void (*PFN_glGetMaterialxv)(GLenum face, GLenum pname, GLfixed *params);
static PFN_glGetMaterialxv glad_glGetMaterialxv = nullptr;
typedef void (*PFN_glGetPointerv)(GLenum pname, void **params);
static PFN_glGetPointerv glad_glGetPointerv = nullptr;
typedef void (*PFN_glGetRenderbufferParameterivOES)(GLenum target, GLenum pname, GLint *params);
static PFN_glGetRenderbufferParameterivOES glad_glGetRenderbufferParameterivOES = nullptr;
typedef const GLubyte * (*PFN_glGetString)(GLenum name);
static PFN_glGetString glad_glGetString = nullptr;
typedef void (*PFN_glGetTexEnvfv)(GLenum target, GLenum pname, GLfloat *params);
static PFN_glGetTexEnvfv glad_glGetTexEnvfv = nullptr;
typedef void (*PFN_glGetTexEnviv)(GLenum target, GLenum pname, GLint *params);
static PFN_glGetTexEnviv glad_glGetTexEnviv = nullptr;
typedef void (*PFN_glGetTexEnvxv)(GLenum target, GLenum pname, GLfixed *params);
static PFN_glGetTexEnvxv glad_glGetTexEnvxv = nullptr;
typedef void (*PFN_glGetTexGenfvOES)(GLenum coord, GLenum pname, GLfloat *params);
static PFN_glGetTexGenfvOES glad_glGetTexGenfvOES = nullptr;
typedef void (*PFN_glGetTexGenivOES)(GLenum coord, GLenum pname, GLint *params);
static PFN_glGetTexGenivOES glad_glGetTexGenivOES = nullptr;
typedef void (*PFN_glGetTexGenxvOES)(GLenum coord, GLenum pname, GLfixed *params);
static PFN_glGetTexGenxvOES glad_glGetTexGenxvOES = nullptr;
typedef void (*PFN_glGetTexParameterfv)(GLenum target, GLenum pname, GLfloat *params);
static PFN_glGetTexParameterfv glad_glGetTexParameterfv = nullptr;
typedef void (*PFN_glGetTexParameteriv)(GLenum target, GLenum pname, GLint *params);
static PFN_glGetTexParameteriv glad_glGetTexParameteriv = nullptr;
typedef void (*PFN_glGetTexParameterxv)(GLenum target, GLenum pname, GLfixed *params);
static PFN_glGetTexParameterxv glad_glGetTexParameterxv = nullptr;
typedef void (*PFN_glHint)(GLenum target, GLenum mode);
static PFN_glHint glad_glHint = nullptr;
typedef GLboolean (*PFN_glIsBuffer)(GLuint buffer);
static PFN_glIsBuffer glad_glIsBuffer = nullptr;
typedef GLboolean (*PFN_glIsEnabled)(GLenum cap);
static PFN_glIsEnabled glad_glIsEnabled = nullptr;
typedef GLboolean (*PFN_glIsFramebufferOES)(GLuint framebuffer);
static PFN_glIsFramebufferOES glad_glIsFramebufferOES = nullptr;
typedef GLboolean (*PFN_glIsRenderbufferOES)(GLuint renderbuffer);
static PFN_glIsRenderbufferOES glad_glIsRenderbufferOES = nullptr;
typedef GLboolean (*PFN_glIsTexture)(GLuint texture);
static PFN_glIsTexture glad_glIsTexture = nullptr;
typedef void (*PFN_glLightModelf)(GLenum pname, GLfloat param);
static PFN_glLightModelf glad_glLightModelf = nullptr;
typedef void (*PFN_glLightModelfv)(GLenum pname, const GLfloat *params);
static PFN_glLightModelfv glad_glLightModelfv = nullptr;
typedef void (*PFN_glLightModelx)(GLenum pname, GLfixed param);
static PFN_glLightModelx glad_glLightModelx = nullptr;
typedef void (*PFN_glLightModelxv)(GLenum pname, const GLfixed *param);
static PFN_glLightModelxv glad_glLightModelxv = nullptr;
typedef void (*PFN_glLightf)(GLenum light, GLenum pname, GLfloat param);
static PFN_glLightf glad_glLightf = nullptr;
typedef void (*PFN_glLightfv)(GLenum light, GLenum pname, const GLfloat *params);
static PFN_glLightfv glad_glLightfv = nullptr;
typedef void (*PFN_glLightx)(GLenum light, GLenum pname, GLfixed param);
static PFN_glLightx glad_glLightx = nullptr;
typedef void (*PFN_glLightxv)(GLenum light, GLenum pname, const GLfixed *params);
static PFN_glLightxv glad_glLightxv = nullptr;
typedef void (*PFN_glLineWidth)(GLfloat width);
static PFN_glLineWidth glad_glLineWidth = nullptr;
typedef void (*PFN_glLineWidthx)(GLfixed width);
static PFN_glLineWidthx glad_glLineWidthx = nullptr;
typedef void (*PFN_glLoadIdentity)(void);
static PFN_glLoadIdentity glad_glLoadIdentity = nullptr;
typedef void (*PFN_glLoadMatrixf)(const GLfloat *m);
static PFN_glLoadMatrixf glad_glLoadMatrixf = nullptr;
typedef void (*PFN_glLoadMatrixx)(const GLfixed *m);
static PFN_glLoadMatrixx glad_glLoadMatrixx = nullptr;
typedef void (*PFN_glLoadPaletteFromModelViewMatrixOES)(void);
static PFN_glLoadPaletteFromModelViewMatrixOES glad_glLoadPaletteFromModelViewMatrixOES = nullptr;
typedef void (*PFN_glLogicOp)(GLenum opcode);
static PFN_glLogicOp glad_glLogicOp = nullptr;
typedef void * (*PFN_glMapBufferOES)(GLenum target, GLenum access);
static PFN_glMapBufferOES glad_glMapBufferOES = nullptr;
typedef void (*PFN_glMaterialf)(GLenum face, GLenum pname, GLfloat param);
static PFN_glMaterialf glad_glMaterialf = nullptr;
typedef void (*PFN_glMaterialfv)(GLenum face, GLenum pname, const GLfloat *params);
static PFN_glMaterialfv glad_glMaterialfv = nullptr;
typedef void (*PFN_glMaterialx)(GLenum face, GLenum pname, GLfixed param);
static PFN_glMaterialx glad_glMaterialx = nullptr;
typedef void (*PFN_glMaterialxv)(GLenum face, GLenum pname, const GLfixed *param);
static PFN_glMaterialxv glad_glMaterialxv = nullptr;
typedef void (*PFN_glMatrixIndexPointerOES)(GLint size, GLenum type, GLsizei stride, const void *pointer);
static PFN_glMatrixIndexPointerOES glad_glMatrixIndexPointerOES = nullptr;
typedef void (*PFN_glMatrixMode)(GLenum mode);
static PFN_glMatrixMode glad_glMatrixMode = nullptr;
typedef void (*PFN_glMultMatrixf)(const GLfloat *m);
static PFN_glMultMatrixf glad_glMultMatrixf = nullptr;
typedef void (*PFN_glMultMatrixx)(const GLfixed *m);
static PFN_glMultMatrixx glad_glMultMatrixx = nullptr;
typedef void (*PFN_glMultiTexCoord4f)(GLenum target, GLfloat s, GLfloat t, GLfloat r, GLfloat q);
static PFN_glMultiTexCoord4f glad_glMultiTexCoord4f = nullptr;
typedef void (*PFN_glMultiTexCoord4x)(GLenum texture, GLfixed s, GLfixed t, GLfixed r, GLfixed q);
static PFN_glMultiTexCoord4x glad_glMultiTexCoord4x = nullptr;
typedef void (*PFN_glNormal3f)(GLfloat nx, GLfloat ny, GLfloat nz);
static PFN_glNormal3f glad_glNormal3f = nullptr;
typedef void (*PFN_glNormal3x)(GLfixed nx, GLfixed ny, GLfixed nz);
static PFN_glNormal3x glad_glNormal3x = nullptr;
typedef void (*PFN_glNormalPointer)(GLenum type, GLsizei stride, const void *pointer);
static PFN_glNormalPointer glad_glNormalPointer = nullptr;
typedef void (*PFN_glOrthof)(GLfloat l, GLfloat r, GLfloat b, GLfloat t, GLfloat n, GLfloat f);
static PFN_glOrthof glad_glOrthof = nullptr;
typedef void (*PFN_glOrthox)(GLfixed l, GLfixed r, GLfixed b, GLfixed t, GLfixed n, GLfixed f);
static PFN_glOrthox glad_glOrthox = nullptr;
typedef void (*PFN_glPixelStorei)(GLenum pname, GLint param);
static PFN_glPixelStorei glad_glPixelStorei = nullptr;
typedef void (*PFN_glPointParameterf)(GLenum pname, GLfloat param);
static PFN_glPointParameterf glad_glPointParameterf = nullptr;
typedef void (*PFN_glPointParameterfv)(GLenum pname, const GLfloat *params);
static PFN_glPointParameterfv glad_glPointParameterfv = nullptr;
typedef void (*PFN_glPointParameterx)(GLenum pname, GLfixed param);
static PFN_glPointParameterx glad_glPointParameterx = nullptr;
typedef void (*PFN_glPointParameterxv)(GLenum pname, const GLfixed *params);
static PFN_glPointParameterxv glad_glPointParameterxv = nullptr;
typedef void (*PFN_glPointSize)(GLfloat size);
static PFN_glPointSize glad_glPointSize = nullptr;
typedef void (*PFN_glPointSizePointerOES)(GLenum type, GLsizei stride, const void *pointer);
static PFN_glPointSizePointerOES glad_glPointSizePointerOES = nullptr;
typedef void (*PFN_glPointSizex)(GLfixed size);
static PFN_glPointSizex glad_glPointSizex = nullptr;
typedef void (*PFN_glPolygonOffset)(GLfloat factor, GLfloat units);
static PFN_glPolygonOffset glad_glPolygonOffset = nullptr;
typedef void (*PFN_glPolygonOffsetx)(GLfixed factor, GLfixed units);
static PFN_glPolygonOffsetx glad_glPolygonOffsetx = nullptr;
typedef void (*PFN_glPopMatrix)(void);
static PFN_glPopMatrix glad_glPopMatrix = nullptr;
typedef void (*PFN_glPushMatrix)(void);
static PFN_glPushMatrix glad_glPushMatrix = nullptr;
typedef GLbitfield (*PFN_glQueryMatrixxOES)(GLfixed *mantissa, GLint *exponent);
static PFN_glQueryMatrixxOES glad_glQueryMatrixxOES = nullptr;
typedef void (*PFN_glReadPixels)(GLint x, GLint y, GLsizei width, GLsizei height, GLenum format, GLenum type, void *pixels);
static PFN_glReadPixels glad_glReadPixels = nullptr;
typedef void (*PFN_glRenderbufferStorageOES)(GLenum target, GLenum internalformat, GLsizei width, GLsizei height);
static PFN_glRenderbufferStorageOES glad_glRenderbufferStorageOES = nullptr;
typedef void (*PFN_glRotatef)(GLfloat angle, GLfloat x, GLfloat y, GLfloat z);
static PFN_glRotatef glad_glRotatef = nullptr;
typedef void (*PFN_glRotatex)(GLfixed angle, GLfixed x, GLfixed y, GLfixed z);
static PFN_glRotatex glad_glRotatex = nullptr;
typedef void (*PFN_glSampleCoverage)(GLfloat value, GLboolean invert);
static PFN_glSampleCoverage glad_glSampleCoverage = nullptr;
typedef void (*PFN_glSampleCoveragex)(GLclampx value, GLboolean invert);
static PFN_glSampleCoveragex glad_glSampleCoveragex = nullptr;
typedef void (*PFN_glScalef)(GLfloat x, GLfloat y, GLfloat z);
static PFN_glScalef glad_glScalef = nullptr;
typedef void (*PFN_glScalex)(GLfixed x, GLfixed y, GLfixed z);
static PFN_glScalex glad_glScalex = nullptr;
typedef void (*PFN_glScissor)(GLint x, GLint y, GLsizei width, GLsizei height);
static PFN_glScissor glad_glScissor = nullptr;
typedef void (*PFN_glShadeModel)(GLenum mode);
static PFN_glShadeModel glad_glShadeModel = nullptr;
typedef void (*PFN_glStencilFunc)(GLenum func, GLint ref, GLuint mask);
static PFN_glStencilFunc glad_glStencilFunc = nullptr;
typedef void (*PFN_glStencilMask)(GLuint mask);
static PFN_glStencilMask glad_glStencilMask = nullptr;
typedef void (*PFN_glStencilOp)(GLenum fail, GLenum zfail, GLenum zpass);
static PFN_glStencilOp glad_glStencilOp = nullptr;
typedef void (*PFN_glTexCoordPointer)(GLint size, GLenum type, GLsizei stride, const void *pointer);
static PFN_glTexCoordPointer glad_glTexCoordPointer = nullptr;
typedef void (*PFN_glTexEnvf)(GLenum target, GLenum pname, GLfloat param);
static PFN_glTexEnvf glad_glTexEnvf = nullptr;
typedef void (*PFN_glTexEnvfv)(GLenum target, GLenum pname, const GLfloat *params);
static PFN_glTexEnvfv glad_glTexEnvfv = nullptr;
typedef void (*PFN_glTexEnvi)(GLenum target, GLenum pname, GLint param);
static PFN_glTexEnvi glad_glTexEnvi = nullptr;
typedef void (*PFN_glTexEnviv)(GLenum target, GLenum pname, const GLint *params);
static PFN_glTexEnviv glad_glTexEnviv = nullptr;
typedef void (*PFN_glTexEnvx)(GLenum target, GLenum pname, GLfixed param);
static PFN_glTexEnvx glad_glTexEnvx = nullptr;
typedef void (*PFN_glTexEnvxv)(GLenum target, GLenum pname, const GLfixed *params);
static PFN_glTexEnvxv glad_glTexEnvxv = nullptr;
typedef void (*PFN_glTexGenfOES)(GLenum coord, GLenum pname, GLfloat param);
static PFN_glTexGenfOES glad_glTexGenfOES = nullptr;
typedef void (*PFN_glTexGenfvOES)(GLenum coord, GLenum pname, const GLfloat *params);
static PFN_glTexGenfvOES glad_glTexGenfvOES = nullptr;
typedef void (*PFN_glTexGeniOES)(GLenum coord, GLenum pname, GLint param);
static PFN_glTexGeniOES glad_glTexGeniOES = nullptr;
typedef void (*PFN_glTexGenivOES)(GLenum coord, GLenum pname, const GLint *params);
static PFN_glTexGenivOES glad_glTexGenivOES = nullptr;
typedef void (*PFN_glTexGenxOES)(GLenum coord, GLenum pname, GLfixed param);
static PFN_glTexGenxOES glad_glTexGenxOES = nullptr;
typedef void (*PFN_glTexGenxvOES)(GLenum coord, GLenum pname, const GLfixed *params);
static PFN_glTexGenxvOES glad_glTexGenxvOES = nullptr;
typedef void (*PFN_glTexImage2D)(GLenum target, GLint level, GLint internalformat, GLsizei width, GLsizei height, GLint border, GLenum format, GLenum type, const void *pixels);
static PFN_glTexImage2D glad_glTexImage2D = nullptr;
typedef void (*PFN_glTexParameterf)(GLenum target, GLenum pname, GLfloat param);
static PFN_glTexParameterf glad_glTexParameterf = nullptr;
typedef void (*PFN_glTexParameterfv)(GLenum target, GLenum pname, const GLfloat *params);
static PFN_glTexParameterfv glad_glTexParameterfv = nullptr;
typedef void (*PFN_glTexParameteri)(GLenum target, GLenum pname, GLint param);
static PFN_glTexParameteri glad_glTexParameteri = nullptr;
typedef void (*PFN_glTexParameteriv)(GLenum target, GLenum pname, const GLint *params);
static PFN_glTexParameteriv glad_glTexParameteriv = nullptr;
typedef void (*PFN_glTexParameterx)(GLenum target, GLenum pname, GLfixed param);
static PFN_glTexParameterx glad_glTexParameterx = nullptr;
typedef void (*PFN_glTexParameterxv)(GLenum target, GLenum pname, const GLfixed *params);
static PFN_glTexParameterxv glad_glTexParameterxv = nullptr;
typedef void (*PFN_glTexSubImage2D)(GLenum target, GLint level, GLint xoffset, GLint yoffset, GLsizei width, GLsizei height, GLenum format, GLenum type, const void *pixels);
static PFN_glTexSubImage2D glad_glTexSubImage2D = nullptr;
typedef void (*PFN_glTranslatef)(GLfloat x, GLfloat y, GLfloat z);
static PFN_glTranslatef glad_glTranslatef = nullptr;
typedef void (*PFN_glTranslatex)(GLfixed x, GLfixed y, GLfixed z);
static PFN_glTranslatex glad_glTranslatex = nullptr;
typedef GLboolean (*PFN_glUnmapBufferOES)(GLenum target);
static PFN_glUnmapBufferOES glad_glUnmapBufferOES = nullptr;
typedef void (*PFN_glVertexPointer)(GLint size, GLenum type, GLsizei stride, const void *pointer);
static PFN_glVertexPointer glad_glVertexPointer = nullptr;
typedef void (*PFN_glViewport)(GLint x, GLint y, GLsizei width, GLsizei height);
static PFN_glViewport glad_glViewport = nullptr;
typedef void (*PFN_glWeightPointerOES)(GLint size, GLenum type, GLsizei stride, const void *pointer);
static PFN_glWeightPointerOES glad_glWeightPointerOES = nullptr;

/* X(name) once per resolvable import. */
#define GLES1_FOREACH(X) \
    X(glActiveTexture) \
    X(glAlphaFunc) \
    X(glAlphaFuncx) \
    X(glBindBuffer) \
    X(glBindFramebufferOES) \
    X(glBindRenderbufferOES) \
    X(glBindTexture) \
    X(glBlendEquationOES) \
    X(glBlendEquationSeparateOES) \
    X(glBlendFunc) \
    X(glBlendFuncSeparateOES) \
    X(glBufferData) \
    X(glBufferSubData) \
    X(glCheckFramebufferStatusOES) \
    X(glClear) \
    X(glClearColor) \
    X(glClearColorx) \
    X(glClearDepthf) \
    X(glClearDepthx) \
    X(glClearStencil) \
    X(glClientActiveTexture) \
    X(glClipPlanef) \
    X(glClipPlanex) \
    X(glColor4f) \
    X(glColor4ub) \
    X(glColor4x) \
    X(glColorMask) \
    X(glColorPointer) \
    X(glCompressedTexImage2D) \
    X(glCompressedTexSubImage2D) \
    X(glCopyTexImage2D) \
    X(glCopyTexSubImage2D) \
    X(glCullFace) \
    X(glCurrentPaletteMatrixOES) \
    X(glDeleteBuffers) \
    X(glDeleteFramebuffersOES) \
    X(glDeleteRenderbuffersOES) \
    X(glDeleteTextures) \
    X(glDepthFunc) \
    X(glDepthMask) \
    X(glDepthRangef) \
    X(glDepthRangex) \
    X(glDisable) \
    X(glDisableClientState) \
    X(glDrawArrays) \
    X(glDrawElements) \
    X(glDrawTexfOES) \
    X(glDrawTexfvOES) \
    X(glDrawTexiOES) \
    X(glDrawTexivOES) \
    X(glDrawTexsOES) \
    X(glDrawTexsvOES) \
    X(glDrawTexxOES) \
    X(glDrawTexxvOES) \
    X(glEGLImageTargetRenderbufferStorageOES) \
    X(glEGLImageTargetTexture2DOES) \
    X(glEnable) \
    X(glEnableClientState) \
    X(glFinish) \
    X(glFlush) \
    X(glFogf) \
    X(glFogfv) \
    X(glFogx) \
    X(glFogxv) \
    X(glFramebufferRenderbufferOES) \
    X(glFramebufferTexture2DOES) \
    X(glFrontFace) \
    X(glFrustumf) \
    X(glFrustumx) \
    X(glGenBuffers) \
    X(glGenFramebuffersOES) \
    X(glGenRenderbuffersOES) \
    X(glGenTextures) \
    X(glGenerateMipmapOES) \
    X(glGetBooleanv) \
    X(glGetBufferParameteriv) \
    X(glGetBufferPointervOES) \
    X(glGetClipPlanef) \
    X(glGetClipPlanex) \
    X(glGetError) \
    X(glGetFixedv) \
    X(glGetFloatv) \
    X(glGetFramebufferAttachmentParameterivOES) \
    X(glGetIntegerv) \
    X(glGetLightfv) \
    X(glGetLightxv) \
    X(glGetMaterialfv) \
    X(glGetMaterialxv) \
    X(glGetPointerv) \
    X(glGetRenderbufferParameterivOES) \
    X(glGetString) \
    X(glGetTexEnvfv) \
    X(glGetTexEnviv) \
    X(glGetTexEnvxv) \
    X(glGetTexGenfvOES) \
    X(glGetTexGenivOES) \
    X(glGetTexGenxvOES) \
    X(glGetTexParameterfv) \
    X(glGetTexParameteriv) \
    X(glGetTexParameterxv) \
    X(glHint) \
    X(glIsBuffer) \
    X(glIsEnabled) \
    X(glIsFramebufferOES) \
    X(glIsRenderbufferOES) \
    X(glIsTexture) \
    X(glLightModelf) \
    X(glLightModelfv) \
    X(glLightModelx) \
    X(glLightModelxv) \
    X(glLightf) \
    X(glLightfv) \
    X(glLightx) \
    X(glLightxv) \
    X(glLineWidth) \
    X(glLineWidthx) \
    X(glLoadIdentity) \
    X(glLoadMatrixf) \
    X(glLoadMatrixx) \
    X(glLoadPaletteFromModelViewMatrixOES) \
    X(glLogicOp) \
    X(glMapBufferOES) \
    X(glMaterialf) \
    X(glMaterialfv) \
    X(glMaterialx) \
    X(glMaterialxv) \
    X(glMatrixIndexPointerOES) \
    X(glMatrixMode) \
    X(glMultMatrixf) \
    X(glMultMatrixx) \
    X(glMultiTexCoord4f) \
    X(glMultiTexCoord4x) \
    X(glNormal3f) \
    X(glNormal3x) \
    X(glNormalPointer) \
    X(glOrthof) \
    X(glOrthox) \
    X(glPixelStorei) \
    X(glPointParameterf) \
    X(glPointParameterfv) \
    X(glPointParameterx) \
    X(glPointParameterxv) \
    X(glPointSize) \
    X(glPointSizePointerOES) \
    X(glPointSizex) \
    X(glPolygonOffset) \
    X(glPolygonOffsetx) \
    X(glPopMatrix) \
    X(glPushMatrix) \
    X(glQueryMatrixxOES) \
    X(glReadPixels) \
    X(glRenderbufferStorageOES) \
    X(glRotatef) \
    X(glRotatex) \
    X(glSampleCoverage) \
    X(glSampleCoveragex) \
    X(glScalef) \
    X(glScalex) \
    X(glScissor) \
    X(glShadeModel) \
    X(glStencilFunc) \
    X(glStencilMask) \
    X(glStencilOp) \
    X(glTexCoordPointer) \
    X(glTexEnvf) \
    X(glTexEnvfv) \
    X(glTexEnvi) \
    X(glTexEnviv) \
    X(glTexEnvx) \
    X(glTexEnvxv) \
    X(glTexGenfOES) \
    X(glTexGenfvOES) \
    X(glTexGeniOES) \
    X(glTexGenivOES) \
    X(glTexGenxOES) \
    X(glTexGenxvOES) \
    X(glTexImage2D) \
    X(glTexParameterf) \
    X(glTexParameterfv) \
    X(glTexParameteri) \
    X(glTexParameteriv) \
    X(glTexParameterx) \
    X(glTexParameterxv) \
    X(glTexSubImage2D) \
    X(glTranslatef) \
    X(glTranslatex) \
    X(glUnmapBufferOES) \
    X(glVertexPointer) \
    X(glViewport) \
    X(glWeightPointerOES) \
    /* end */
