/*
 * The GLES 1.1 import table.
 *
 * thunks/khronos/gles2.cpp - generated from glad for a GLES2 game - answer none
 * of them, which is why this file exists rather than an addition to that one.
 *
 * ---------------------------------------------------------------------------
 * Where fixed function actually comes from, which is not where it looks like
 *
 * The obvious provider is libGLESv1_CM.so.1, and it is present on both the
 * build image and the console, so an early triage note concluded the
 * harness could run this game. That was wrong, and wrong in the way that costs
 * the most: the file is glvnd's vendor-neutral *dispatch stub*. There is no
 * implementation behind it unless some vendor library registers one, and
 * Debian's Mesa is built without GLES1. The symptom is not a missing symbol -
 * it is eglCreateContext returning EGL_BAD_ALLOC for a client version of 1
 * while version 2 succeeds, which reads like an EGL configuration problem and
 * cost two full debugging iterations chasing EGL attributes.
 *
 * Measured in the build image, all three under qemu-arm + llvmpipe:
 *
 *   ES1 context        FAIL, EGL_BAD_ALLOC (0x3003)
 *   ES2 context        OK
 *   desktop GL context OK - 4.5 Compatibility Profile
 *
 * The last line is the answer. Fixed function is not a GLES concept that
 * desktop GL happens to share; it is *desktop GL 1.1*, and GLES 1.1 is the
 * subset. Mesa's libGL exports all 190 of the names this game imports - the
 * fixed-point glClearColorx family and the OES extension entry points
 * included - and a compatibility-profile context runs them natively. Verified
 * end to end: glMatrixMode/glVertexPointer/glDrawArrays draw a triangle that
 * comes back out of glReadPixels, glGetError clean.
 *
 * So the provider chain is: whatever exposes fixed function on this machine.
 * On the console that is expected to be libmali (which does export
 * glMatrixMode); under the harness it is Mesa's libGL. Neither is hardcoded -
 * gl_provider_open() tries them in order and the log says which one won,
 * because "which GL am I actually on" is the first question worth answering
 * when the screen is black.
 * ---------------------------------------------------------------------------
 *
 * The prototypes come from thunks/khronos/gles1_funcs.hpp, generated by
 * tools/generate_gles1.py out of the system GLES headers. They are typed, not
 * void*, because the game is armeabi-v7a (softfp) and this loader is hardfp:
 * thunk_gen_dyn.h reads each signature at compile time and inserts an ABI
 * bridge exactly where a float crosses over. In fixed-function GL that is most
 * calls, and a wrong prototype is not a compile error - it is garbage geometry.
 */
#include <dlfcn.h>
#include <stdio.h>
#include <string.h>

#include <SDL2/SDL.h>

#include "so_util.h"
#include "thunk_gen.h"
#include "thunk_gen_dyn.h"
#include "trace.h"

#include "gles1_funcs.hpp"

static int          symtable_gles1_index = 0;
DynLibFunction      symtable_gles1[512]  = {};

static void *g_gl_provider      = nullptr;
static const char *g_gl_provider_name = "(none)";

/*
 * Candidates in priority order.
 *
 * The console's Mali blob first: if the hardware speaks fixed function, going
 * through it is both faster and closer to what the game was built against.
 * Mesa's libGL second, which is what the harness has. The glvnd stub is
 * deliberately *not* in this list - it resolves every name and implements
 * none, so trying it would produce a table full of pointers that segfault on
 * first use, which is strictly worse than not resolving at all.
 */
static const char *kProviders[] = {
    "libmali.so.1",
    "libGL.so.1",
    nullptr,
};

/*
 * Prove the library really implements fixed function before adopting it.
 *
 * Presence of a soname says nothing: that is exactly the trap libGLESv1_CM set.
 * glMatrixMode is the cheapest possible probe - it exists in no GLES2-only
 * library and in every fixed-function one.
 */
static bool provider_has_fixed_function(void *h)
{
    return h && dlsym(h, "glMatrixMode") != nullptr;
}

const char *gl_provider_name(void) { return g_gl_provider_name; }

bool gl_provider_open(void)
{
    if (g_gl_provider)
        return true;

    for (int i = 0; kProviders[i]; i++) {
        void *h = dlopen(kProviders[i], RTLD_NOW | RTLD_GLOBAL);
        if (!h)
            continue;
        if (!provider_has_fixed_function(h)) {
            trace("GL provider %s has no fixed function, skipping", kProviders[i]);
            dlclose(h);
            continue;
        }
        g_gl_provider      = h;
        g_gl_provider_name = kProviders[i];
        trace("GL provider: %s (fixed function present)", kProviders[i]);
        return true;
    }

    trace("no GL provider implements fixed function - the game cannot render");
    return false;
}

/*
 * Resolve one name.
 *
 * dlsym on the provider first, because that is the library we verified. Only
 * then the driver's own GetProcAddress, which is how extension entry points
 * are meant to be found and is the path that answers the *OES names on a
 * driver that exposes them as extensions rather than as exports.
 */
static void *gl1_resolve(const char *symbol)
{
    if (g_gl_provider) {
        void *f = dlsym(g_gl_provider, symbol);
        if (f)
            return f;
    }
    return SDL_GL_GetProcAddress(symbol);
}

#define PTR_RESOLVE(x) \
    resolve_thunked<&glad_##x>(#x, symtable_gles1_index, symtable_gles1, gl1_resolve)

#define RESOLVE_ONE(x) glad_##x = (PFN_##x)PTR_RESOLVE(x);

/*
 * Fill the table from the live driver.
 *
 * Must run with a context current: a GL entry point resolved without one is
 * allowed to come back null, and on some drivers comes back non-null but
 * unusable. Anything still null afterwards is reported by name rather than
 * silently entered into the table, so an import the game needs surfaces here
 * instead of as a jump to address zero from inside a static constructor.
 */
void load_gles1_funcs(void)
{
    if (!gl_provider_open())
        return;

    GLES1_FOREACH(RESOLVE_ONE)

    trace("GLES1 table: %d/%d imports resolved from %s",
          symtable_gles1_index, 190, g_gl_provider_name);
}

/* How many entries actually made it, for the harness and for main.cpp. */
int gles1_resolved_count(void) { return symtable_gles1_index; }
