#!/usr/bin/env bash
#
# Collect the shared libraries the port has to carry, into libs.armhf/.
#
# A PortMaster port lands on a console whose userland is years older than the
# machine it was cross-compiled on, so anything the CFW does not already
# provide has to travel in the zip. The split is not "everything ldd prints" —
# three families of library MUST come from the device instead, and shipping
# them is worse than shipping nothing:
#
#   * glibc and its interpreter. The kernel maps the device's ld-linux, and a
#     second glibc inside the same process is not a fallback, it is a crash.
#   * libSDL2. Every CFW builds its own against its own video backend — the
#     R36S runs KMSDRM with no X server, while a Debian SDL2 asks for X11,
#     Wayland and PulseAudio and finds none of them.
#   * the GL/EGL stack. Those are the Mali blobs, matched to the kernel driver.
#
# Everything else is ours to carry. The closure therefore descends only
# through libraries we bundle: what a device-provided library needs is the
# device's business, not the port's.
#
# Run it inside the build container:
# or, equivalently, `make libs`.
set -euo pipefail

BIN=${1:-build/katamari}
OUT=${2:-build/libs.armhf}
READELF=${READELF:-arm-linux-gnueabihf-readelf}

# Where an armhf .so can live in the build image: the multiarch dir for the
# libraries we install with apt, the cross toolchain's sysroot for glibc.
SEARCH_DIRS="/usr/lib/arm-linux-gnueabihf /lib/arm-linux-gnueabihf /usr/arm-linux-gnueabihf/lib"

[ -f "$BIN" ] || { echo "collect_libs: no such binary: $BIN (run make first)" >&2; exit 1; }

# Why a library is left behind. A non-empty answer means "device-provided",
# and it is printed in the manifest so the decision stays auditable.
device_reason() {
    case "$1" in
        ld-linux-armhf.so.3|libc.so.6|libm.so.6|libdl.so.2|libpthread.so.0|\
        librt.so.1|libresolv.so.2|libanl.so.1|libnsl.so.*|libutil.so.1)
            echo "glibc: must be the device's own, the kernel maps its interpreter" ;;
        libSDL2-2.0.so.0)
            echo "the CFW's SDL2 is built for the device's video backend (KMSDRM, no X11)" ;;
        libEGL.so.*|libGLESv2.so.*|libGLESv1_CM.so.*|libGL.so.*|libgbm.so.*|libdrm.so.*|libmali*)
            echo "Mali blob, matched to the kernel driver" ;;
        *)
            echo "" ;;
    esac
}

find_lib() {
    local soname=$1 d
    for d in $SEARCH_DIRS; do
        [ -e "$d/$soname" ] && { readlink -f "$d/$soname"; return 0; }
    done
    return 1
}

needed_of() {
    "$READELF" -d "$1" 2>/dev/null | sed -n 's/.*Shared library: \[\(.*\)\]/\1/p'
}

rm -rf "$OUT"
mkdir -p "$OUT/licenses"

seen=" "
bundled=""
skipped=""
queue=$(needed_of "$BIN")

while [ -n "${queue// /}" ]; do
    next=""
    for soname in $queue; do
        case "$seen" in *" $soname "*) continue ;; esac
        seen="$seen$soname "

        reason=$(device_reason "$soname")
        if [ -n "$reason" ]; then
            skipped="$skipped$soname|$reason
"
            continue
        fi

        path=$(find_lib "$soname") || {
            echo "collect_libs: $soname is needed but is nowhere in the image." >&2
            echo "              Either install it or add it to device_reason() with a reason." >&2
            exit 1
        }

        # Copy under the SONAME, not the versioned filename: the SONAME is
        # what the dynamic linker asks for. Only one copy, no symlink chain —
        # exFAT (what an SD card usually is) has no symlinks.
        cp -f "$path" "$OUT/$soname"
        chmod 0644 "$OUT/$soname"

        # PortMaster releases carry the copyright terms of every shared
        # library they redistribute. Resolve the owning Debian package from
        # the exact file selected above and preserve its machine-readable
        # copyright file next to the generated bundle. Failing here is safer
        # than producing a legally incomplete release that otherwise works.
        owner=$(dpkg-query -S "$path" 2>/dev/null | sed -n '1p')
        package=${owner%%:*}
        copyright="/usr/share/doc/$package/copyright"
        if [ -z "$owner" ] || [ ! -f "$copyright" ]; then
            echo "collect_libs: no copyright file found for $soname ($path)" >&2
            exit 1
        fi
        cp -Lf "$copyright" "$OUT/licenses/$soname.copyright"
        chmod 0644 "$OUT/licenses/$soname.copyright"

        bundled="$bundled$soname|$(basename "$path")|$(( $(stat -c%s "$path") / 1024 )) KB
"
        next="$next $(needed_of "$path")"
    done
    queue=$next
done

{
    echo "# libs.armhf — generated by tools/collect_libs.sh, do not edit."
    echo "# Everything the port carries, and everything it deliberately does not."
    echo
    echo "## bundled"
    printf '%s' "$bundled" | sort | awk -F'|' '{printf "%-22s %-24s %10s\n", $1, $2, $3}'
    echo
    echo "## left to the device"
    printf '%s' "$skipped" | sort | awk -F'|' '{printf "%-22s %s\n", $1, $2}'
} > "$OUT/MANIFEST.txt"

cat "$OUT/MANIFEST.txt"
echo
echo "collect_libs: $(printf '%s' "$bundled" | grep -c . ) libraries in $OUT ($(du -sk "$OUT" | cut -f1) KB)"
