#!/usr/bin/env python3
"""
Generate the GLES 1.1 import table for the symbols Katamari actually calls.

Why this exists at all: the game is fixed-function. It imports 190 gl* entry
points and not one shader call, so thunks/khronos/gles2.cpp - written for a
GLES2 game and generated from glad - answers none of them.

Why it is generated rather than written by hand: every one of those 190 needs a
*typed* prototype, not a void*. The game is armeabi-v7a, which passes floats in
core registers (softfp); this loader is built hardfp. thunk_gen_dyn.h inspects
each prototype at compile time and inserts an ABI bridge only where a float
actually crosses the boundary - and in fixed-function GL that is most of them
(glRotatef, glColor4f, glMaterialfv...). Getting one prototype wrong is a
wrong-register bug that shows up as garbage geometry, not as a compile error.
The system headers already have all 190 declarations, correctly. So we read
them instead of retyping them.

Run inside the build image, where /usr/include/GLES exists:
    docker run --rm -v "$PWD":/src -w /src katamari-build \
        python3 tools/generate_gles1.py
"""
import re
import sys
import pathlib

HEADERS = [
    "/usr/include/GLES/gl.h",
    "/usr/include/GLES/glext.h",
]

OUT = pathlib.Path("thunks/khronos/gles1_funcs.hpp")

# One prototype per line in these headers, in one of two shapes:
#   GL_API void GL_APIENTRY glAlphaFunc (GLenum func, GLfloat ref);
#   GL_APICALL void GL_APIENTRY glFoo (void);
PROTO = re.compile(
    r"^\s*GL_API(?:CALL)?\s+(?P<ret>[A-Za-z_][\w \*]*?)\s*GL_APIENTRY\s+"
    r"(?P<name>gl\w+)\s*\((?P<args>[^)]*)\)\s*;",
    re.MULTILINE,
)


def wanted_symbols(path):
    """The gl* imports the game declares, one per line (from readelf UND)."""
    names = set()
    for line in pathlib.Path(path).read_text().splitlines():
        line = line.strip()
        if line.startswith("gl"):
            names.add(line)
    return names


def main():
    if len(sys.argv) < 2:
        sys.exit("usage: generate_gles1.py <undefined-symbols.txt>")

    want = wanted_symbols(sys.argv[1])

    protos = {}
    for h in HEADERS:
        try:
            text = pathlib.Path(h).read_text()
        except FileNotFoundError:
            sys.exit(f"missing {h} - run this inside the build image")
        for m in PROTO.finditer(text):
            name = m.group("name")
            # glext.h redeclares a few core entry points; first one wins, and
            # gl.h is read first on purpose because its spelling is canonical.
            if name not in protos:
                protos[name] = (m.group("ret").strip(), m.group("args").strip())

    have = want & protos.keys()
    missing = sorted(want - protos.keys())

    lines = [
        "/*",
        " * GENERATED by tools/generate_gles1.py - do not edit.",
        " *",
        " * Typed prototypes for the GLES 1.1 entry points Katamari imports,",
        " * lifted from the system GLES headers so the softfp/hardfp bridges in",
        " * thunk_gen_dyn.h can be generated from real signatures.",
        " */",
        "#pragma once",
        "",
        "#include <GLES/gl.h>",
        "#include <GLES/glext.h>",
        "",
    ]

    for name in sorted(have):
        ret, args = protos[name]
        lines.append(f"typedef {ret} (*PFN_{name})({args});")
        lines.append(f"static PFN_{name} glad_{name} = nullptr;")

    lines.append("")
    lines.append("/* X(name) once per resolvable import. */")
    lines.append("#define GLES1_FOREACH(X) \\")
    for name in sorted(have):
        lines.append(f"    X({name}) \\")
    lines.append("    /* end */")
    lines.append("")

    if missing:
        lines.append("/*")
        lines.append(" * Declared by the game but absent from the system headers, so they")
        lines.append(" * cannot be given a typed bridge here. gles1.cpp stubs these and")
        lines.append(" * traces loudly if the engine ever calls one - which tells us")
        lines.append(" * whether they were real uses or just linker noise.")
        lines.append(" */")
        lines.append("#define GLES1_UNTYPED(X) \\")
        for name in missing:
            lines.append(f"    X({name}) \\")
        lines.append("    /* end */")
        lines.append("")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n".join(lines))

    print(f"{len(have)}/{len(want)} imports typed from the headers -> {OUT}")
    if missing:
        print(f"{len(missing)} without a declaration: {' '.join(missing)}")


if __name__ == "__main__":
    main()
