/*
 * The bionic-only imports the generated libc table cannot express.
 *
 * tools/generate_libc.sh builds thunks/libc/generated/impl_tab.h by walking a
 * host glibc header dump, so it can only emit a symbol that (a) glibc also has
 * and (b) has a non-variadic prototype it can reproduce. Everything in this
 * file fails one of those two tests, and the harness sees the result as M2:
 *
 *     unresolved symbol: __atomic_cmpxchg      (bionic-only, no glibc twin)
 *     unresolved symbol: __page_size           (OBJECT, not a function)
 *     unresolved symbol: fcntl                 (variadic)
 *     unresolved symbol: readdir_r             (struct layout differs)
 *     ...
 *
 * Grep impl_tab.h for the names below and every one of them is there, commented
 * out, as THUNK_MISSING or "(TODO impl variadic)". That is the generator saying
 * "I saw this and refused", not "I did not know about it" - so the fix belongs
 * here, in a hand-written override table, and not in the generator.
 */
#include <dirent.h>
#include <errno.h>
#include <fcntl.h>
#include <atomic>
#include <stdarg.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#if defined(_WIN32)
#ifndef WIN32_LEAN_AND_MEAN
#define WIN32_LEAN_AND_MEAN
#endif
#include <windows.h>
#include <io.h>
#else
#include <unistd.h>
#endif

#include "so_util.h"
#include "thunk_gen.h"
#include "trace.h"

/* ------------------------------------------------------------------ atomics
 *
 * bionic's legacy atomic helpers, exported from libc for the benefit of
 * pre-C11 code generated by the old NDK. They are not compiler builtins and
 * they are not in glibc under any name, so the generator listed all four as
 * THUNK_MISSING (impl_tab.h:72-75).
 *
 * The signatures and, more importantly, the *return conventions* are from
 * bionic/libc/arch-arm/bionic/atomics_arm.c - they are not the obvious ones:
 *
 *   __atomic_cmpxchg returns 0 on SUCCESS (it is a "did it fail" flag, the
 *   inverse of what compare_and_swap builtins return); __atomic_inc and
 *   __atomic_dec return the value *before* the operation, not after.
 *
 * Getting either backwards produces a game that runs: a refcount that returns
 * the post-decrement value frees one release too early, and the crash lands in
 * an unrelated destructor thousands of frames later. So they are spelled out
 * rather than aliased to anything that looks close.
 *
 * All four carry a full barrier in bionic; __ATOMIC_SEQ_CST reproduces that.
 */
extern "C" int bionic_atomic_cmpxchg(int old_value, int new_value, volatile int *ptr)
{
    int expected = old_value;
    /* Strong CAS: bionic's is a ldrex/strex loop, so a spurious failure would
     * be a behaviour change the caller cannot see coming. */
    bool swapped = std::atomic_ref<int>(*const_cast<int *>(ptr))
        .compare_exchange_strong(expected, new_value,
                                 std::memory_order_seq_cst,
                                 std::memory_order_seq_cst);
    return swapped ? 0 : 1;
}

extern "C" int bionic_atomic_swap(int new_value, volatile int *ptr)
{
    return std::atomic_ref<int>(*const_cast<int *>(ptr))
        .exchange(new_value, std::memory_order_seq_cst);
}

extern "C" int bionic_atomic_inc(volatile int *ptr)
{
    return std::atomic_ref<int>(*const_cast<int *>(ptr))
        .fetch_add(1, std::memory_order_seq_cst);
}

extern "C" int bionic_atomic_dec(volatile int *ptr)
{
    return std::atomic_ref<int>(*const_cast<int *>(ptr))
        .fetch_sub(1, std::memory_order_seq_cst);
}

/* ------------------------------------------------------------- C++ runtime
 *
 * __cxa_guard_acquire/__cxa_guard_release are bound straight to the host
 * libstdc++ rather than reimplemented, and that is safe for one specific
 * reason: both sides are ARM EABI, where the guard variable is a 4-byte word
 * and "already constructed" is bit 0 of its first byte. The Itanium ABI
 * version everyone else uses is 8 bytes with a different done-flag, which is
 * what makes this look risky when it is not.
 *
 * That matters because the fast path is *not* ours. The game's own code tests
 * the guard byte inline (ldrb / tst #1) before it ever calls in, so whatever
 * implementation answers here has to agree with that test bit. libstdc++'s
 * EABI branch sets exactly that bit; bionic's sets the whole word to 1, which
 * has bit 0 set too. Both work; a hand-rolled one that stored, say, 2 would
 * loop forever re-running the constructor.
 *
 * Reimplementing was the alternative and was rejected: a correct version needs
 * the blocked-thread wait, and the game runs its static initialisers from more
 * than one thread. Borrowing libstdc++'s means the loader and the game share
 * one guard implementation instead of racing two.
 */
#if !defined(_WIN32)
extern "C" int __cxa_guard_acquire(void *guard);
extern "C" void __cxa_guard_release(void *guard);
#else
static SRWLOCK g_guard_lock = SRWLOCK_INIT;
static CONDITION_VARIABLE g_guard_changed = CONDITION_VARIABLE_INIT;

/* Itanium/Bionic guard words are eight bytes. Bit zero of the first word is
 * the completed flag; bit one is private to this host and marks an active
 * initializer. The second word records its owner so recursive initialization
 * fails instead of hanging the process. */
extern "C" int __cxa_guard_acquire(void *guard)
{
    if (!guard)
        return 0;

    auto *state_word = static_cast<uint32_t *>(guard);
    auto *owner_word = reinterpret_cast<uint32_t *>(
        static_cast<unsigned char *>(guard) + sizeof(uint32_t));
    std::atomic_ref<uint32_t> state(*state_word);
    if (state.load(std::memory_order_acquire) & 1)
        return 0;

    const DWORD self = GetCurrentThreadId();
    AcquireSRWLockExclusive(&g_guard_lock);
    for (;;) {
        const uint32_t value = state.load(std::memory_order_relaxed);
        if (value & 1) {
            ReleaseSRWLockExclusive(&g_guard_lock);
            return 0;
        }
        if (!(value & 2)) {
            *owner_word = self;
            state.store(value | 2, std::memory_order_release);
            ReleaseSRWLockExclusive(&g_guard_lock);
            return 1;
        }
        if (*owner_word == self) {
            ReleaseSRWLockExclusive(&g_guard_lock);
            abort();
        }
        SleepConditionVariableSRW(&g_guard_changed, &g_guard_lock,
                                  INFINITE, 0);
    }
}

extern "C" void __cxa_guard_release(void *guard)
{
    if (!guard)
        return;
    auto *state_word = static_cast<uint32_t *>(guard);
    auto *owner_word = reinterpret_cast<uint32_t *>(
        static_cast<unsigned char *>(guard) + sizeof(uint32_t));
    std::atomic_ref<uint32_t> state(*state_word);
    AcquireSRWLockExclusive(&g_guard_lock);
    *owner_word = 0;
    state.store(1, std::memory_order_release);
    WakeAllConditionVariable(&g_guard_changed);
    ReleaseSRWLockExclusive(&g_guard_lock);
}
#endif

/*
 * Wrapped, not bound directly, so the reasoning above can be checked rather
 * than believed.
 *
 * The claim is that the host's EABI guard convention and the game's inline
 * `ldr / ands #1` test agree. If they did not, the failure would be silent and
 * indistinguishable from what this port was already chasing: a getter for a
 * function-local static returning an object whose constructor never ran, i.e.
 * exactly "an object with a null vtable". Counting acquires against releases
 * settles it - every acquire that returns non-zero must be followed by a
 * release, and any guard that gets acquired twice was never marked done.
 */
extern "C" int bionic_cxa_guard_acquire(void *guard)
{
    int rc = __cxa_guard_acquire(guard);
    if (getenv("KATAMARI_TRACE_GUARDS"))
        trace("cxa_guard_acquire(%p) -> %d  [word=0x%08x]",
              guard, rc, *(unsigned *)guard);
    return rc;
}

extern "C" void bionic_cxa_guard_release(void *guard)
{
    __cxa_guard_release(guard);
    if (getenv("KATAMARI_TRACE_GUARDS"))
        trace("cxa_guard_release(%p)     [word=0x%08x]",
              guard, *(unsigned *)guard);
}

/*
 * __cxa_pure_virtual is ours on purpose, not the host's.
 *
 * It appears ~5000 times in the run log because it is a vtable filler, one
 * slot per abstract method, and it is only ever reached on a genuine bug: a
 * virtual call on a half-constructed or already-destroyed object. libstdc++'s
 * version routes through std::terminate, which unwinds - and unwinding out of
 * a module this loader mapped goes through our own __gnu_Unwind_Find_exidx
 * shim, so a fault there would print a stack from the unwinder instead of from
 * the call site. Aborting immediately keeps the crash handler's backtrace
 * pointing at the object that was actually broken.
 */
extern "C" void bionic_cxa_pure_virtual(void)
{
    fatal("pure virtual method called - object was destroyed or not yet constructed");
    abort();
}

/* ---------------------------------------------------------- data objects
 *
 * Three OBJECT imports, not functions. On a real device these come out of the
 * module's own crtbegin_so.o (__dso_handle) or out of libc's data segment.
 *
 * __dso_handle only has to be a stable, unique, non-NULL address: the game
 * passes it as the third argument of __cxa_atexit so the runtime can group
 * destructors by owning DSO. Its contents are never read.
 */
static char bionic_dso_handle;

/*
 * __page_size is read by the engine's allocator to align mmap requests. It is
 * queried rather than hard-coded to 4096: the R36S runs an aarch64 kernel and
 * the build host may not use the same page size the 2013 armeabi build assumed,
 * and an mmap length rounded to the wrong granule fails with EINVAL at the
 * first large allocation.
 */
#if defined(_WIN32)
static unsigned int windows_page_size()
{
    SYSTEM_INFO system_info{};
    GetSystemInfo(&system_info);
    return (unsigned int)system_info.dwPageSize;
}
static unsigned int bionic_page_size = windows_page_size();
#else
static unsigned int bionic_page_size = (unsigned int)getpagesize();
#endif

/*
 * tzname is the one data symbol that is *not* just an address.
 *
 * The layout matches (two char* on both sides), so the array itself could be
 * aliased to glibc's. What does not match is when it becomes valid: bionic
 * fills tzname during libc startup, glibc leaves it untouched until the first
 * tzset() or localtime() call. The game reads tzname[] straight out of a save
 * timestamp formatter, before it has called anything that would populate it,
 * and would get uninitialised pointers.
 *
 * So the host array is used directly - which keeps it live if the game later
 * goes through our localtime() - and tzset() is forced once at load time to
 * guarantee it is populated before the first read.
 */
namespace {
#if defined(_WIN32)
static char windows_timezone_utc[] = "UTC";
static char *bionic_tzname[2] = {
    windows_timezone_utc,
    windows_timezone_utc,
};
#else
struct TzInit {
    TzInit() { tzset(); }
};
[[maybe_unused]] const TzInit tz_init;
#endif
}

/* ---------------------------------------------------------------- fcntl
 *
 * Variadic, which is the whole reason the generator skipped it
 * ("(TODO impl variadic) THUNK_DIRECT(fcntl)", impl_tab.h:18). Unpacked by
 * hand exactly like open() and ioctl() in symtab_libm.cpp.
 *
 * The command number is forwarded unchanged. That is correct here because this
 * loader is built without _FILE_OFFSET_BITS=64, so the host's fcntl is the
 * plain one and passes the command to the kernel as-is - the same thing bionic
 * does. Were it the LFS variant it would silently rewrite F_GETLK into
 * F_GETLK64 and then read a struct flock the game never wrote.
 *
 * Reading the third argument unconditionally is safe under AAPCS: for the
 * commands that take none it just picks up whatever is in r2 and the kernel
 * ignores it.
 */
extern "C" int bionic_fcntl(int fd, int cmd, ...)
{
    va_list ap;
    va_start(ap, cmd);
#if defined(_WIN32)
    int arg = 0;
    switch (cmd) {
    case 0: /* F_DUPFD */
    case 2: /* F_SETFD */
    case 4: /* F_SETFL */
        arg = va_arg(ap, int);
        break;
    default:
        break;
    }
    va_end(ap);
    switch (cmd) {
    case 0: {
        /* _dup() allocates the lowest available descriptor; retain temporary
         * duplicates until one satisfies POSIX F_DUPFD's minimum. */
        int *reserved = nullptr;
        size_t count = 0;
        size_t capacity = 0;
        for (;;) {
            const int duplicate = _dup(fd);
            if (duplicate < 0) {
                for (size_t i = 0; i < count; ++i)
                    _close(reserved[i]);
                free(reserved);
                return -1;
            }
            if (duplicate >= arg) {
                for (size_t i = 0; i < count; ++i)
                    _close(reserved[i]);
                free(reserved);
                return duplicate;
            }
            if (count == capacity) {
                const size_t next_capacity = capacity ? capacity * 2 : 8;
                void *next = realloc(reserved,
                                     next_capacity * sizeof(*reserved));
                if (!next) {
                    _close(duplicate);
                    for (size_t i = 0; i < count; ++i)
                        _close(reserved[i]);
                    free(reserved);
                    errno = ENOMEM;
                    return -1;
                }
                reserved = static_cast<int *>(next);
                capacity = next_capacity;
            }
            reserved[count++] = duplicate;
        }
    }
    case 1: return 0;        /* F_GETFD */
    case 2: return 0;        /* F_SETFD: host descriptors are non-inheritable */
    case 3: return 0;        /* F_GETFL */
    case 4: (void)arg; return 0; /* F_SETFL: regular-file flags are advisory */
    default:
        errno = EINVAL;
        return -1;
    }
#else
    void *arg = va_arg(ap, void *);
    va_end(ap);
    return fcntl(fd, cmd, arg);
#endif
}

/* --------------------------------------------------------------- readdir_r
 *
 * bionic's struct dirent is glibc's struct dirent64, not glibc's struct
 * dirent: 64-bit d_ino and d_off, which puts d_name at offset 19 instead of
 * 11. This loader is built without _FILE_OFFSET_BITS=64, so the host's plain
 * dirent is the 32-bit one and every field after d_off sits eight bytes early.
 *
 * The game reads d_name to filter asset directories. Handing it the host
 * layout does not crash - it silently reads the tail of d_off plus the first
 * bytes of the name, so every entry looks like garbage and the directory scan
 * finds nothing. That is a M6 "0 assets opened" that says nothing about
 * dirent.
 *
 * The generator could not have caught this: readdir_r is in symtab_exclude
 * (line 11, "deprecated") because gmloader-next ships a real bionic libc.so
 * for it. This port does not.
 */
#if defined(_WIN32)
static uint8_t windows_dirent_type(int type)
{
    if (type == S_IFIFO) return 1;
    if (type == S_IFCHR) return 2;
    if (type == S_IFDIR) return 4;
    if (type == S_IFBLK) return 6;
    if (type == S_IFREG) return 8;
    if (type == S_IFLNK) return 10;
    if (type == S_IFSOCK) return 12;
    return 0;
}

static void convert_windows_dirent(const struct dirent &host,
                                   struct bionic_dirent *entry)
{
    entry->d_ino = (uint64_t)(uint32_t)host.d_ino;
    entry->d_off = (int64_t)host.d_off;
    entry->d_type = windows_dirent_type(host.d_type);
    const size_t name_len = strnlen(host.d_name, sizeof(entry->d_name) - 1);
    memcpy(entry->d_name, host.d_name, name_len);
    entry->d_name[name_len] = '\0';
    entry->d_reclen = (uint16_t)((offsetof(struct bionic_dirent, d_name) +
                                  name_len + 1 + 7) & ~(size_t)7);
}

extern "C" struct bionic_dirent *bionic_readdir(DIR *dir)
{
    if (!dir)
        return NULL;
    struct dirent *host = readdir(dir);
    if (!host)
        return NULL;
    static thread_local struct bionic_dirent converted;
    convert_windows_dirent(*host, &converted);
    return &converted;
}

extern "C" int bionic_readdir_r(DIR *dir, struct bionic_dirent *entry,
                                struct bionic_dirent **result)
{
    if (!dir || !entry || !result)
        return EINVAL;
    struct dirent host_entry{};
    struct dirent *host = NULL;
    const int rc = readdir_r(dir, &host_entry, &host);
    if (rc != 0) {
        *result = NULL;
        return rc;
    }
    if (!host) {
        *result = NULL;
        return 0;
    }
    convert_windows_dirent(*host, entry);
    *result = entry;
    return 0;
}
#else
/* struct bionic_dirent is already declared in thunks/libc/bionic_file.h,
 * transcribed from bionic/libc/include/dirent.h and until now unused - the
 * generated table binds readdir() straight to the host's, which is the bug
 * described above. Only the assertions are new. */
static_assert(offsetof(struct bionic_dirent, d_name) == 19,
              "bionic puts d_name at 19; the game indexes it there");
static_assert(sizeof(struct bionic_dirent) == sizeof(struct dirent64),
              "bionic's dirent is glibc's dirent64 with the same padding");

/*
 * Built on readdir64() rather than the host's readdir_r() on purpose. glibc
 * has deprecated readdir_r and its remaining implementation still fills the
 * *host* layout, so it would have to be converted anyway - and going through
 * readdir64 keeps the conversion in one place and out of a deprecated path.
 *
 * The thread-safety readdir_r nominally promises is not reproduced: readdir64
 * returns libc's per-DIR buffer, so two threads walking the same DIR would
 * still race. That matches what the engine actually does (one DIR per scan,
 * on the thread that opened it) and the alternative - a lock keyed on DIR* -
 * would serialise nothing real.
 */
static void convert_dirent64(const struct dirent64 &host,
                            struct bionic_dirent *entry)
{
    entry->d_ino  = (uint64_t)host.d_ino;
    entry->d_off  = (int64_t)host.d_off;
    entry->d_type = (uint8_t)host.d_type;

    size_t name_len = strnlen(host.d_name, sizeof(entry->d_name) - 1);
    memcpy(entry->d_name, host.d_name, name_len);
    entry->d_name[name_len] = '\0';

    /* Android's record contains 64-bit ino/off even on 32-bit ABIs. Compute
     * the guest record length from the guest layout, never from glibc's
     * architecture-dependent struct dirent. */
    entry->d_reclen = (uint16_t)((offsetof(struct bionic_dirent, d_name)
                                  + name_len + 1 + 7) & ~(size_t)7);
}

/*
 * UE3 1.07 imports readdir(), not just readdir_r(). On 32-bit glibc the plain
 * struct dirent may use 32-bit ino_t/off_t, while bionic's public dirent has
 * 64-bit d_ino/d_off. Returning glibc's pointer directly shifts d_name and
 * makes a successful directory walk look empty to the guest.
 *
 * readdir's contract only promises the returned pointer until the next call on
 * the directory stream; a thread-local converted record is therefore enough
 * and avoids owning guest-visible heap memory.
 */
extern "C" struct bionic_dirent *bionic_readdir(DIR *dir)
{
    if (!dir)
        return NULL;

    errno = 0;
    struct dirent64 *host = readdir64(dir);
    if (!host)
        return NULL;

    static thread_local struct bionic_dirent converted;
    convert_dirent64(*host, &converted);
    return &converted;
}

extern "C" int bionic_readdir_r(DIR *dir, struct bionic_dirent *entry,
                                struct bionic_dirent **result)
{
    if (!dir || !entry || !result)
        return EINVAL;

    /* readdir64 returns NULL both at end-of-directory and on error, and only
     * errno tells them apart; readdir_r must return 0 for the former. */
    errno = 0;
    struct dirent64 *host = readdir64(dir);
    if (!host) {
        *result = NULL;
        return errno;
    }

    convert_dirent64(*host, entry);
    *result = entry;
    return 0;
}
#endif

DynLibFunction symtable_bionic[] = {
    /* No float crosses any of these boundaries, so select_either() resolves
     * every one to a direct pointer and no ABI bridge is generated. */
    THUNK_SPECIFIC("__atomic_cmpxchg", bionic_atomic_cmpxchg),
    THUNK_SPECIFIC("__cxa_guard_acquire", bionic_cxa_guard_acquire),
    THUNK_SPECIFIC("__cxa_guard_release", bionic_cxa_guard_release),
    THUNK_SPECIFIC("__atomic_swap",    bionic_atomic_swap),
    THUNK_SPECIFIC("__atomic_inc",     bionic_atomic_inc),
    THUNK_SPECIFIC("__atomic_dec",     bionic_atomic_dec),

    NO_THUNK("__cxa_pure_virtual",  (uintptr_t)&bionic_cxa_pure_virtual),

    /* Data, not code: the loader writes these addresses into the relocation
     * slot and the game dereferences them itself. */
    NO_THUNK("__dso_handle", (uintptr_t)&bionic_dso_handle),
    NO_THUNK("__page_size",  (uintptr_t)&bionic_page_size),
#if defined(_WIN32)
    NO_THUNK("tzname",       (uintptr_t)&bionic_tzname),
#else
    NO_THUNK("tzname",       (uintptr_t)&tzname),
#endif

    NO_THUNK("fcntl",     (uintptr_t)&bionic_fcntl),
    NO_THUNK("readdir",   (uintptr_t)&bionic_readdir),
    NO_THUNK("readdir_r", (uintptr_t)&bionic_readdir_r),

    { NULL, 0 },
};
