#include "jni_internals.h"
#include "android_input_codes.h"

/*
 * Tiny read-only framework classes used by the original UE3 Android glue.
 *
 * UE3 intentionally asks JNI for android.view.MotionEvent/KeyEvent constants
 * instead of compiling their numeric values into the native library.  On
 * Android these are static int fields.  The fake JNI represents primitive
 * static fields by storing the value directly in FieldId::offset (its
 * GetStaticIntField implementation returns that slot as the value).
 */

namespace {

#define STATIC_INT_FIELD(classref, fieldname, fieldvalue) \
    { .clazz=&classref, .name=#fieldname, .signature="I", \
      .offset=(uintptr_t)(fieldvalue), .is_static=1 }

struct MotionEventClass {
    static Class clazz;
};

const FieldId motion_fields[] = {
    STATIC_INT_FIELD(MotionEventClass::clazz, ACTION_DOWN,
                     android_input::kActionDown),
    STATIC_INT_FIELD(MotionEventClass::clazz, ACTION_UP,
                     android_input::kActionUp),
    STATIC_INT_FIELD(MotionEventClass::clazz, ACTION_MOVE,
                     android_input::kActionMove),
    STATIC_INT_FIELD(MotionEventClass::clazz, ACTION_CANCEL,
                     android_input::kActionCancel),
    STATIC_INT_FIELD(MotionEventClass::clazz, ACTION_OUTSIDE,
                     android_input::kActionOutside),
    STATIC_INT_FIELD(MotionEventClass::clazz, ACTION_POINTER_DOWN,
                     android_input::kActionPointerDown),
    STATIC_INT_FIELD(MotionEventClass::clazz, ACTION_POINTER_UP,
                     android_input::kActionPointerUp),
    STATIC_INT_FIELD(MotionEventClass::clazz, AXIS_X, android_input::kAxisX),
    STATIC_INT_FIELD(MotionEventClass::clazz, AXIS_Y, android_input::kAxisY),
    STATIC_INT_FIELD(MotionEventClass::clazz, AXIS_VSCROLL,
                     android_input::kAxisVscroll),
    STATIC_INT_FIELD(MotionEventClass::clazz, AXIS_HSCROLL,
                     android_input::kAxisHscroll),
    STATIC_INT_FIELD(MotionEventClass::clazz, AXIS_Z, android_input::kAxisZ),
    STATIC_INT_FIELD(MotionEventClass::clazz, AXIS_RZ, android_input::kAxisRz),
    STATIC_INT_FIELD(MotionEventClass::clazz, AXIS_LTRIGGER,
                     android_input::kAxisLtrigger),
    STATIC_INT_FIELD(MotionEventClass::clazz, AXIS_RTRIGGER,
                     android_input::kAxisRtrigger),
    {},
};

Class MotionEventClass::clazz = {
    .classpath = "android/view/MotionEvent",
    .classname = "MotionEvent",
    .managed_methods = nullptr,
    .native_methods = nullptr,
    .fields = motion_fields,
    .instance_size = 0,
};

struct KeyEventClass {
    static Class clazz;
};

/* Android KeyEvent values have remained stable for these legacy API-1 keys. */
const FieldId key_fields[] = {
    STATIC_INT_FIELD(KeyEventClass::clazz, ACTION_DOWN,
                     android_input::kActionDown),
    STATIC_INT_FIELD(KeyEventClass::clazz, ACTION_UP,
                     android_input::kActionUp),
    STATIC_INT_FIELD(KeyEventClass::clazz, ACTION_MULTIPLE,
                     android_input::kActionMove),

    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_HOME,
                     android_input::kKeyHome),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BACK,
                     android_input::kKeyBack),

    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_0, android_input::kKey0),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_1, android_input::kKey0 + 1),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_2, android_input::kKey0 + 2),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_3, android_input::kKey0 + 3),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_4, android_input::kKey0 + 4),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_5, android_input::kKey0 + 5),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_6, android_input::kKey0 + 6),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_7, android_input::kKey0 + 7),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_8, android_input::kKey0 + 8),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_9, android_input::kKey0 + 9),

    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_STAR,
                     android_input::kKeyStar),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_DPAD_UP,
                     android_input::kKeyDpadUp),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_DPAD_DOWN,
                     android_input::kKeyDpadDown),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_DPAD_LEFT,
                     android_input::kKeyDpadLeft),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_DPAD_RIGHT,
                     android_input::kKeyDpadRight),

    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_A, android_input::kKeyA),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_B, android_input::kKeyA + 1),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_C, android_input::kKeyA + 2),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_D, android_input::kKeyA + 3),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_E, android_input::kKeyA + 4),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F, android_input::kKeyA + 5),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_G, android_input::kKeyA + 6),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_H, android_input::kKeyA + 7),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_I, android_input::kKeyA + 8),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_J, android_input::kKeyA + 9),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_K, android_input::kKeyA + 10),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_L, android_input::kKeyA + 11),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_M, android_input::kKeyA + 12),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_N, android_input::kKeyA + 13),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_O, android_input::kKeyA + 14),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_P, android_input::kKeyA + 15),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_Q, android_input::kKeyA + 16),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_R, android_input::kKeyA + 17),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_S, android_input::kKeyA + 18),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_T, android_input::kKeyA + 19),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_U, android_input::kKeyA + 20),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_V, android_input::kKeyA + 21),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_W, android_input::kKeyA + 22),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_X, android_input::kKeyA + 23),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_Y, android_input::kKeyA + 24),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_Z, android_input::kKeyA + 25),

    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_COMMA,
                     android_input::kKeyComma),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_PERIOD,
                     android_input::kKeyPeriod),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_ALT_LEFT,
                     android_input::kKeyAltLeft),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_ALT_RIGHT,
                     android_input::kKeyAltRight),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_SHIFT_LEFT,
                     android_input::kKeyShiftLeft),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_SHIFT_RIGHT,
                     android_input::kKeyShiftRight),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_TAB,
                     android_input::kKeyTab),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_SPACE,
                     android_input::kKeySpace),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_ENTER,
                     android_input::kKeyEnter),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_DEL,
                     android_input::kKeyDel),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_GRAVE,
                     android_input::kKeyGrave),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_MINUS,
                     android_input::kKeyMinus),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_EQUALS,
                     android_input::kKeyEquals),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_LEFT_BRACKET,
                     android_input::kKeyLeftBracket),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_RIGHT_BRACKET,
                     android_input::kKeyRightBracket),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BACKSLASH,
                     android_input::kKeyBackslash),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_SEMICOLON,
                     android_input::kKeySemicolon),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_APOSTROPHE,
                     android_input::kKeyApostrophe),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_SLASH,
                     android_input::kKeySlash),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUM,
                     android_input::kKeyNum),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_PLUS,
                     android_input::kKeyPlus),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_MENU,
                     android_input::kKeyMenu),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_SEARCH,
                     android_input::kKeySearch),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_PAGE_UP,
                     android_input::kKeyPageUp),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_PAGE_DOWN,
                     android_input::kKeyPageDown),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_A,
                     android_input::kKeyButtonA),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_B,
                     android_input::kKeyButtonB),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_C,
                     android_input::kKeyButtonC),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_X,
                     android_input::kKeyButtonX),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_Y,
                     android_input::kKeyButtonY),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_Z,
                     android_input::kKeyButtonZ),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_L1,
                     android_input::kKeyButtonL1),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_R1,
                     android_input::kKeyButtonR1),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_L2,
                     android_input::kKeyButtonL2),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_R2,
                     android_input::kKeyButtonR2),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_THUMBL,
                     android_input::kKeyButtonThumbL),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_THUMBR,
                     android_input::kKeyButtonThumbR),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_START,
                     android_input::kKeyButtonStart),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_SELECT,
                     android_input::kKeyButtonSelect),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_MODE,
                     android_input::kKeyButtonMode),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_ESCAPE,
                     android_input::kKeyEscape),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_CTRL_LEFT,
                     android_input::kKeyCtrlLeft),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_CTRL_RIGHT,
                     android_input::kKeyCtrlRight),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_CAPS_LOCK,
                     android_input::kKeyCapsLock),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_SCROLL_LOCK,
                     android_input::kKeyScrollLock),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_META_LEFT,
                     android_input::kKeyMetaLeft),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_META_RIGHT,
                     android_input::kKeyMetaRight),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_SYSRQ,
                     android_input::kKeySysRq),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BREAK,
                     android_input::kKeyBreak),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_MOVE_END,
                     android_input::kKeyMoveEnd),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_INSERT,
                     android_input::kKeyInsert),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F1,
                     android_input::kKeyF1),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F2,
                     android_input::kKeyF1 + 1),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F3,
                     android_input::kKeyF1 + 2),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F4,
                     android_input::kKeyF1 + 3),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F5,
                     android_input::kKeyF1 + 4),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F6,
                     android_input::kKeyF1 + 5),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F7,
                     android_input::kKeyF1 + 6),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F8,
                     android_input::kKeyF1 + 7),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F9,
                     android_input::kKeyF1 + 8),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F10,
                     android_input::kKeyF1 + 9),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F11,
                     android_input::kKeyF1 + 10),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_F12,
                     android_input::kKeyF1 + 11),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUM_LOCK,
                     android_input::kKeyNumLock),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_0,
                     android_input::kKeyNumpad0),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_1,
                     android_input::kKeyNumpad0 + 1),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_2,
                     android_input::kKeyNumpad0 + 2),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_3,
                     android_input::kKeyNumpad0 + 3),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_4,
                     android_input::kKeyNumpad0 + 4),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_5,
                     android_input::kKeyNumpad0 + 5),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_6,
                     android_input::kKeyNumpad0 + 6),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_7,
                     android_input::kKeyNumpad0 + 7),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_8,
                     android_input::kKeyNumpad0 + 8),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_9,
                     android_input::kKeyNumpad0 + 9),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_DIVIDE,
                     android_input::kKeyNumpadDivide),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_MULTIPLY,
                     android_input::kKeyNumpadMultiply),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_SUBTRACT,
                     android_input::kKeyNumpadSubtract),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_ADD,
                     android_input::kKeyNumpadAdd),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_DOT,
                     android_input::kKeyNumpadDot),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_COMMA,
                     android_input::kKeyNumpadComma),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_ENTER,
                     android_input::kKeyNumpadEnter),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_NUMPAD_EQUALS,
                     android_input::kKeyNumpadEquals),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_1,
                     android_input::kKeyButton1),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_2,
                     android_input::kKeyButton1 + 1),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_3,
                     android_input::kKeyButton1 + 2),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_4,
                     android_input::kKeyButton1 + 3),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_5,
                     android_input::kKeyButton1 + 4),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_6,
                     android_input::kKeyButton1 + 5),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_7,
                     android_input::kKeyButton1 + 6),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_8,
                     android_input::kKeyButton1 + 7),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_9,
                     android_input::kKeyButton1 + 8),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_10,
                     android_input::kKeyButton1 + 9),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_11,
                     android_input::kKeyButton1 + 10),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_12,
                     android_input::kKeyButton1 + 11),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_13,
                     android_input::kKeyButton1 + 12),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_14,
                     android_input::kKeyButton1 + 13),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_15,
                     android_input::kKeyButton1 + 14),
    STATIC_INT_FIELD(KeyEventClass::clazz, KEYCODE_BUTTON_16,
                     android_input::kKeyButton1 + 15),
    {},
};

Class KeyEventClass::clazz = {
    .classpath = "android/view/KeyEvent",
    .classname = "KeyEvent",
    .managed_methods = nullptr,
    .native_methods = nullptr,
    .fields = key_fields,
    .instance_size = 0,
};

const int registered_motion = ClassRegistry::register_class(MotionEventClass::clazz);
const int registered_key = ClassRegistry::register_class(KeyEventClass::clazz);

} // namespace
